---
apiVersion: v1
kind: Service
metadata:
  name: testproj-preview
  namespace: testproj
  labels:
    app: testproj
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: testproj

---
apiVersion: v1
kind: Service
metadata:
  name: testproj-active
  namespace: testproj
  labels:
    app: testproj
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: testproj
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

